### PR TITLE
update to frontend

### PR DESCRIPTION
**Pull request by Georgefemiwise**

### CODE REVIEW

**Comment by Georgefemiwise** [comment]
state manager needs to be updated, 
currently, it doesn't update a single question when answered.

**Comment by Georgefemiwise** [comment]
everything is good, need to take it individually.

**Review by Georgefemiwise — COMMENTED** [review]
the frontend needs to stand

**Review by richod1 — APPROVED** [review]
i hate tailwind.css

**Review by richod1 — APPROVED** [review]
Route structure is quit good

**Review by richod1 — APPROVED** [review]
cool logo 100%

**Review by richod1 — APPROVED** [review]
review done on branch

**Pull request merged**
